import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import {
  Bell, Boxes, Building2, CalendarDays, Check, ChevronDown, CircleDollarSign,
  ClipboardList, Clock3, FileCheck2, Gauge, LayoutDashboard, Menu, MoreHorizontal,
  PackageSearch, Plus, Printer, Search, Settings, ShieldCheck, TrendingUp, Users,
  Wrench, X, Minus, ArrowDownToLine, History, Eye, FileDown,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "PontoTech Toledo | Gestão de assistência técnica" },
    { name: "description", content: "Gestão de ordens de serviço, clientes, garantias, estoque e financeiro para assistências técnicas." },
    { property: "og:title", content: "PontoTech Toledo" },
    { property: "og:description", content: "Operação completa para assistências técnicas." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ] }),
  component: Index,
});

type Section = "Visão geral" | "Ordens de serviço" | "Clientes" | "Garantias" | "Estoque" | "Financeiro" | "Equipe" | "Administração";
type Customer = { id:string; name:string; document:string; phone:string; email:string };
type Stock = { id:string; sku:string; name:string; category:string; supplier:string; location:string; quantity:number; minimum:number; cost:number; price:number; movements:{type:string; quantity:number; date:string; note:string}[] };
type Order = { id:string; customerId:string; client:string; document:string; device:string; serial:string; issue:string; stage:string; tech:string; total:number; due:string; tone:string; parts:{name:string; quantity:number; price:number}[] };
type Warranty = { id:string; orderId:string; customer:string; device:string; starts:string; expires:string; coverage:string; status:string };
type DialogKind = "order" | "customer" | "stock" | "movement" | "warranty" | "orderView" | "warrantyView" | null;

const initialCustomers: Customer[] = [
  {id:"c1",name:"Mariana Costa",document:"123.456.789-00",phone:"(45) 99912-4401",email:"mariana@email.com"},
  {id:"c2",name:"Oficina Paraná",document:"12.345.678/0001-90",phone:"(45) 3055-1280",email:"contato@oficinaparana.com"},
  {id:"c3",name:"João Mendes",document:"987.654.321-00",phone:"(45) 99821-7720",email:"joao@email.com"},
  {id:"c4",name:"Clínica Vital",document:"28.456.741/0001-12",phone:"(45) 3035-8800",email:"ti@clinicavital.com"},
];
const initialStock: Stock[] = [
  {id:"p1",sku:"TEL-IP14-OLED",name:"Tela OLED iPhone 14 Pro",category:"Telas",supplier:"Tech Parts",location:"A-03",quantity:8,minimum:3,cost:410,price:650,movements:[{type:"Entrada",quantity:10,date:"22/09/2026",note:"Nota 1842"},{type:"Saída OS-1048",quantity:2,date:"23/09/2026",note:"Consumo em reparo"}]},
  {id:"p2",sku:"BAT-S23",name:"Bateria Galaxy S23",category:"Baterias",supplier:"Mobile Sul",location:"B-11",quantity:2,minimum:4,cost:92,price:190,movements:[{type:"Entrada",quantity:5,date:"20/09/2026",note:"Reposição"},{type:"Saída",quantity:3,date:"23/09/2026",note:"Ordens atendidas"}]},
  {id:"p3",sku:"SSD-NVME-1TB",name:"SSD NVMe 1 TB",category:"Armazenamento",supplier:"Info Atacado",location:"C-04",quantity:12,minimum:4,cost:285,price:450,movements:[{type:"Entrada",quantity:12,date:"21/09/2026",note:"Compra mensal"}]},
];
const initialOrders: Order[] = [
  {id:"OS-1048",customerId:"c1",client:"Mariana Costa",document:"123.456.789-00",device:"iPhone 14 Pro",serial:"IMEI 352099001234567",issue:"Tela sem imagem após queda",stage:"Em reparo",tech:"Carlos",total:780,due:"Hoje, 16:00",tone:"blue",parts:[{name:"Tela OLED iPhone 14 Pro",quantity:1,price:650}]},
  {id:"OS-1047",customerId:"c2",client:"Oficina Paraná",document:"12.345.678/0001-90",device:"Notebook Dell G15",serial:"SN-DG15-8821",issue:"Não liga",stage:"Aguardando aprovação",tech:"Ana",total:460,due:"Hoje, 18:00",tone:"amber",parts:[]},
  {id:"OS-1046",customerId:"c3",client:"João Mendes",document:"987.654.321-00",device:"Galaxy S23",serial:"IMEI 351234567891230",issue:"Bateria descarrega rapidamente",stage:"Pronto para entrega",tech:"Rafael",total:320,due:"Ontem",tone:"green",parts:[{name:"Bateria Galaxy S23",quantity:1,price:190}]},
  {id:"OS-1045",customerId:"c4",client:"Clínica Vital",document:"28.456.741/0001-12",device:"MacBook Air M2",serial:"C02MA2VITAL",issue:"Superaquecimento",stage:"Diagnóstico",tech:"Carlos",total:0,due:"Amanhã",tone:"violet",parts:[]},
];
const initialWarranties: Warranty[] = [{id:"GAR-7A91C2",orderId:"OS-1046",customer:"João Mendes",device:"Galaxy S23",starts:"23/09/2026",expires:"22/12/2026",coverage:"Bateria substituída e serviço de instalação",status:"Ativa"}];
const nav: {label:Section;icon:typeof Gauge;group?:string}[] = [
  {label:"Visão geral",icon:LayoutDashboard},{label:"Ordens de serviço",icon:ClipboardList,group:"OPERAÇÃO"},{label:"Clientes",icon:Users},{label:"Garantias",icon:ShieldCheck},{label:"Estoque",icon:Boxes,group:"GESTÃO"},{label:"Financeiro",icon:CircleDollarSign},{label:"Equipe",icon:Wrench},{label:"Administração",icon:Building2,group:"PLATAFORMA"},
];
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const today=()=>new Date().toLocaleDateString("pt-BR");
const addDays=(days:number)=>{const d=new Date();d.setDate(d.getDate()+days);return d.toLocaleDateString("pt-BR")};
const escapeHtml=(s:string)=>s.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c] ?? c);

function printDocument(title:string, body:string){
  const popup=window.open("","_blank","width=900,height=760"); if(!popup)return;
  popup.document.write(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>${escapeHtml(title)}</title><style>@page{size:A4;margin:16mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#172033;margin:0;font-size:12px}.head{display:flex;justify-content:space-between;border-bottom:3px solid #0878bd;padding-bottom:16px;margin-bottom:22px}.brand{font-size:24px;font-weight:800}.muted{color:#667085}.badge{border:1px solid #0878bd;color:#0878bd;padding:5px 9px;font-weight:700}h1{font-size:20px;margin:0 0 4px}h2{font-size:12px;text-transform:uppercase;color:#667085;margin:22px 0 8px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px 28px}.box{border:1px solid #d9dee8;padding:12px;margin:8px 0}.row{display:flex;justify-content:space-between;border-bottom:1px solid #e8ebf0;padding:8px 0}.total{font-size:16px;font-weight:700}.sign{display:grid;grid-template-columns:1fr 1fr;gap:60px;margin-top:70px;text-align:center}.line{border-top:1px solid #172033;padding-top:7px}.no-print{margin:0 0 18px}@media print{.no-print{display:none}}</style></head><body><button class="no-print" onclick="window.print()">Imprimir / Salvar como PDF</button><div class="head"><div><div class="brand">PontoTech Toledo</div><div class="muted">Assistência técnica • Documento operacional</div></div><div class="badge">${escapeHtml(title)}</div></div>${body}<div class="sign"><div class="line">Responsável técnico</div><div class="line">Cliente</div></div><script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`); popup.document.close();
}

function Index(){
  const [section,setSection]=useState<Section>("Visão geral"),[menuOpen,setMenuOpen]=useState(false),[dialog,setDialog]=useState<DialogKind>(null),[search,setSearch]=useState("");
  const [customers,setCustomers]=useState(initialCustomers),[stock,setStock]=useState(initialStock),[orders,setOrders]=useState(initialOrders),[warranties,setWarranties]=useState(initialWarranties);
  const [selectedOrder,setSelectedOrder]=useState<Order|null>(null),[selectedWarranty,setSelectedWarranty]=useState<Warranty|null>(null),[selectedStock,setSelectedStock]=useState<Stock|null>(null);
  const q=search.toLowerCase();
  const filteredOrders=useMemo(()=>orders.filter(o=>Object.values(o).join(" ").toLowerCase().includes(q)),[orders,q]);
  const open=(kind:DialogKind)=>setDialog(kind);
  const action=()=>{if(section==="Clientes")open("customer");else if(section==="Estoque")open("stock");else if(section==="Garantias")open("warranty");else open("order")};
  const labels:Partial<Record<Section,string>>={Clientes:"Novo cliente",Estoque:"Nova peça",Garantias:"Emitir garantia","Ordens de serviço":"Nova ordem"};
  return <div className="min-h-screen bg-background text-foreground">
    <Sidebar section={section} setSection={s=>{setSection(s);setMenuOpen(false);setSearch("")}} open={menuOpen} close={()=>setMenuOpen(false)}/>
    <main className="min-h-screen lg:pl-64">
      <header className="sticky top-0 z-30 flex h-16 items-center gap-3 border-b bg-background/95 px-4 backdrop-blur md:px-7"><Button variant="ghost" size="icon" className="lg:hidden" aria-label="Abrir menu" onClick={()=>setMenuOpen(true)}><Menu/></Button><div className="relative hidden max-w-xl flex-1 md:block"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar nesta área…" className="h-10 border-0 bg-muted pl-10 shadow-none"/></div><div className="ml-auto flex items-center gap-2"><Button variant="ghost" size="icon" aria-label="Notificações"><Bell/></Button><span className="grid size-8 place-items-center rounded-md bg-primary font-bold text-primary-foreground">PT</span><span className="hidden text-sm font-semibold sm:block">PontoTech Toledo</span><ChevronDown className="hidden size-4 sm:block"/></div></header>
      <div className="mx-auto max-w-[1600px] px-4 py-6 md:px-7 md:py-8"><div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-1 text-sm font-medium text-muted-foreground">Quarta-feira, 23 de setembro</p><h1 className="text-2xl font-bold md:text-3xl">{section}</h1><p className="mt-1 text-sm text-muted-foreground">Olá, Paulo. Sua operação está sob controle.</p></div>{["Clientes","Estoque","Garantias","Ordens de serviço","Visão geral"].includes(section)&&<Button className="h-10 w-full sm:w-auto" onClick={action}><Plus/>{labels[section]??"Nova ordem"}</Button>}</div>
        {section==="Visão geral"&&<Dashboard orders={filteredOrders} stock={stock} onNew={()=>open("order")} onSection={setSection}/>} 
        {section==="Ordens de serviço"&&<OrdersView orders={filteredOrders} onNew={()=>open("order")} onView={o=>{setSelectedOrder(o);open("orderView")}}/>}
        {section==="Clientes"&&<CustomersView customers={customers.filter(c=>`${c.name} ${c.document} ${c.phone}`.toLowerCase().includes(q))} orders={orders} onNew={()=>open("customer")}/>} 
        {section==="Estoque"&&<StockView stock={stock.filter(s=>`${s.name} ${s.sku} ${s.category}`.toLowerCase().includes(q))} onNew={()=>open("stock")} onMove={s=>{setSelectedStock(s);open("movement")}}/>}
        {section==="Garantias"&&<WarrantyView warranties={warranties} onNew={()=>open("warranty")} onView={w=>{setSelectedWarranty(w);open("warrantyView")}}/>}
        {["Financeiro","Equipe","Administração"].includes(section)&&<Placeholder section={section}/>} 
      </div>
    </main>
    <CustomerDialog open={dialog==="customer"} close={()=>setDialog(null)} onSave={c=>{setCustomers(v=>[...v,c]);setDialog(null)}}/>
    <StockDialog open={dialog==="stock"} close={()=>setDialog(null)} onSave={s=>{setStock(v=>[...v,s]);setDialog(null)}}/>
    <MovementDialog open={dialog==="movement"} item={selectedStock} close={()=>setDialog(null)} onSave={(id,amount,type,note)=>{setStock(v=>v.map(s=>s.id===id?{...s,quantity:s.quantity+(type==="entry"?amount:-amount),movements:[{type:type==="entry"?"Entrada":"Saída",quantity:amount,date:today(),note},...s.movements]}:s));setDialog(null)}}/>
    <OrderDialog open={dialog==="order"} customers={customers} stock={stock} close={()=>setDialog(null)} onSave={(o,part)=>{setOrders(v=>[o,...v]);if(part)setStock(v=>v.map(s=>s.id===part.id?{...s,quantity:s.quantity-part.quantity,movements:[{type:`Saída ${o.id}`,quantity:part.quantity,date:today(),note:"Consumo automático na ordem"},...s.movements]}:s));setSelectedOrder(o);setDialog("orderView")}}/>
    <WarrantyDialog open={dialog==="warranty"} orders={orders} close={()=>setDialog(null)} onSave={w=>{setWarranties(v=>[w,...v]);setSelectedWarranty(w);setDialog("warrantyView")}}/>
    <OrderDocumentDialog open={dialog==="orderView"} order={selectedOrder} close={()=>setDialog(null)}/>
    <WarrantyDocumentDialog open={dialog==="warrantyView"} warranty={selectedWarranty} close={()=>setDialog(null)}/>
  </div>
}

function Sidebar({section,setSection,open,close}:{section:Section;setSection:(s:Section)=>void;open:boolean;close:()=>void}){return <>{open&&<Button variant="ghost" className="fixed inset-0 z-40 h-auto w-auto rounded-none bg-foreground/30 lg:hidden" onClick={close} aria-label="Fechar menu"/>}<aside className={`fixed inset-y-0 left-0 z-50 flex w-64 flex-col border-r bg-sidebar transition-transform lg:translate-x-0 ${open?"translate-x-0":"-translate-x-full"}`}><div className="flex h-16 items-center border-b px-5"><div className="grid size-9 place-items-center rounded-md bg-primary text-primary-foreground"><Wrench className="size-5"/></div><div className="ml-3"><div className="text-base font-extrabold leading-4">PontoTech</div><div className="text-[10px] font-bold uppercase text-primary">Gestão inteligente</div></div><Button variant="ghost" size="icon" onClick={close} className="ml-auto lg:hidden"><X/></Button></div><nav className="flex-1 overflow-y-auto px-3 py-4">{nav.map((item,i)=><div key={item.label}>{item.group&&<p className={`mb-2 px-3 text-[10px] font-bold text-muted-foreground ${i?"mt-6":""}`}>{item.group}</p>}<Button variant="ghost" onClick={()=>setSection(item.label)} className={`mb-1 h-10 w-full justify-start gap-3 px-3 ${section===item.label?"bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground":"text-sidebar-foreground"}`}><item.icon className="size-[18px]"/>{item.label}</Button></div>)}</nav><div className="border-t p-3"><div className="rounded-md bg-muted p-3 text-xs font-semibold"><Settings className="mb-2 size-4 text-primary"/>Configurações da empresa</div></div></aside></>}
function Dashboard({orders,stock,onNew,onSection}:{orders:Order[];stock:Stock[];onNew:()=>void;onSection:(s:Section)=>void}){const metrics=[{label:"Ordens em andamento",value:String(orders.length),note:"Operação atual",icon:ClipboardList},{label:"Aguardando aprovação",value:String(orders.filter(o=>o.stage.includes("aprovação")).length),note:"Orçamentos pendentes",icon:Clock3},{label:"Receita estimada",value:money(orders.reduce((a,o)=>a+o.total,0)),note:"Ordens listadas",icon:TrendingUp},{label:"Estoque baixo",value:String(stock.filter(s=>s.quantity<=s.minimum).length),note:"Itens para repor",icon:PackageSearch}];return <div className="space-y-6"><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(m=><article key={m.label} className="rounded-lg border bg-card p-5 shadow-card"><div className="grid size-9 place-items-center rounded-md bg-muted text-primary"><m.icon className="size-[18px]"/></div><p className="mt-5 text-2xl font-bold">{m.value}</p><p className="mt-1 text-sm font-medium">{m.label}</p><p className="mt-2 text-xs text-muted-foreground">{m.note}</p></article>)}</section><section className="grid gap-6 xl:grid-cols-[1.65fr_1fr]"><div className="min-w-0 rounded-lg border bg-card shadow-card"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-bold">Ordens recentes</h2><p className="text-xs text-muted-foreground">Clientes, equipamentos e prazos</p></div><Button variant="ghost" size="sm" onClick={()=>onSection("Ordens de serviço")}>Ver todas</Button></div><OrderTable orders={orders}/></div><div className="rounded-lg border bg-card p-5 shadow-card"><h2 className="font-bold">Ações rápidas</h2><div className="mt-5 grid gap-2"><Button onClick={onNew}><Plus/>Nova ordem</Button><Button variant="outline" onClick={()=>onSection("Clientes")}><Users/>Gerenciar clientes</Button><Button variant="outline" onClick={()=>onSection("Estoque")}><Boxes/>Gerenciar estoque</Button><Button variant="outline" onClick={()=>onSection("Garantias")}><ShieldCheck/>Emitir garantia</Button></div></div></section><section className="grid gap-4 md:grid-cols-3"><InfoCard icon={History} title="Histórico preservado" text="Movimentações de peças ficam registradas por data e origem."/><InfoCard icon={CalendarDays} title="Agenda de hoje" text="3 entregas e 1 retorno em garantia programados."/><InfoCard icon={FileCheck2} title="Documentos prontos" text="Ordens e garantias podem ser impressas ou salvas em PDF."/></section></div>}
function InfoCard({icon:Icon,title,text}:{icon:typeof History;title:string;text:string}){return <article className="rounded-lg border bg-card p-5 shadow-card"><Icon className="size-5 text-primary"/><h3 className="mt-4 font-bold">{title}</h3><p className="mt-1 text-sm text-muted-foreground">{text}</p></article>}
function OrderTable({orders,onView}:{orders:Order[];onView?:(o:Order)=>void}){return <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="text-xs text-muted-foreground"><th className="px-5 py-3">ORDEM</th><th className="px-3 py-3">CLIENTE / EQUIPAMENTO</th><th className="px-3 py-3">STATUS</th><th className="px-3 py-3">VALOR</th><th className="px-5 py-3">AÇÕES</th></tr></thead><tbody>{orders.map(o=><tr key={o.id} className="border-t hover:bg-muted/50"><td className="px-5 py-4 font-bold text-primary">{o.id}</td><td className="px-3 py-4"><div className="font-semibold">{o.client}</div><div className="text-xs text-muted-foreground">{o.device}</div></td><td className="px-3 py-4"><span className={`status status-${o.tone}`}><i/>{o.stage}</span></td><td className="px-3 py-4 font-semibold">{o.total?money(o.total):"—"}</td><td className="px-5 py-4">{onView?<Button variant="ghost" size="sm" onClick={()=>onView(o)}><Eye/>Abrir</Button>:<span className="text-muted-foreground">{o.due}</span>}</td></tr>)}</tbody></table>{!orders.length&&<Empty text="Nenhuma ordem encontrada."/>}</div>}
function OrdersView({orders,onNew,onView}:{orders:Order[];onNew:()=>void;onView:(o:Order)=>void}){return <section className="rounded-lg border bg-card shadow-card"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-bold">Todas as ordens</h2><p className="text-xs text-muted-foreground">Pesquise por número, cliente, documento ou equipamento</p></div><Button onClick={onNew}><Plus/>Nova ordem</Button></div><OrderTable orders={orders} onView={onView}/></section>}
function CustomersView({customers,orders,onNew}:{customers:Customer[];orders:Order[];onNew:()=>void}){return <section className="rounded-lg border bg-card shadow-card"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-bold">Cadastro de clientes</h2><p className="text-xs text-muted-foreground">Pessoas físicas e empresas com histórico completo</p></div><Button onClick={onNew}><Plus/>Novo cliente</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr className="text-xs text-muted-foreground"><th className="px-5 py-3">NOME</th><th className="px-3 py-3">DOCUMENTO</th><th className="px-3 py-3">CONTATO</th><th className="px-5 py-3">ATENDIMENTOS</th></tr></thead><tbody>{customers.map(c=><tr key={c.id} className="border-t"><td className="px-5 py-4 font-semibold">{c.name}</td><td className="px-3 py-4">{c.document}</td><td className="px-3 py-4"><div>{c.phone}</div><div className="text-xs text-muted-foreground">{c.email}</div></td><td className="px-5 py-4 font-semibold">{orders.filter(o=>o.customerId===c.id).length}</td></tr>)}</tbody></table>{!customers.length&&<Empty text="Nenhum cliente encontrado."/>}</div></section>}
function StockView({stock,onNew,onMove}:{stock:Stock[];onNew:()=>void;onMove:(s:Stock)=>void}){return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3"><Stat label="Peças cadastradas" value={String(stock.length)}/><Stat label="Custo em estoque" value={money(stock.reduce((a,s)=>a+s.cost*s.quantity,0))}/><Stat label="Reposição necessária" value={String(stock.filter(s=>s.quantity<=s.minimum).length)}/></div><section className="rounded-lg border bg-card shadow-card"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-bold">Peças e produtos</h2><p className="text-xs text-muted-foreground">Saldo, preço, localização e histórico de movimentações</p></div><Button onClick={onNew}><Plus/>Nova peça</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead><tr className="text-xs text-muted-foreground"><th className="px-5 py-3">PEÇA / SKU</th><th className="px-3 py-3">LOCAL</th><th className="px-3 py-3">SALDO</th><th className="px-3 py-3">CUSTO / VENDA</th><th className="px-5 py-3">MOVIMENTAR</th></tr></thead><tbody>{stock.map(s=><tr key={s.id} className="border-t"><td className="px-5 py-4"><div className="font-semibold">{s.name}</div><div className="text-xs text-muted-foreground">{s.sku} • {s.category}</div></td><td className="px-3 py-4">{s.location}</td><td className="px-3 py-4"><span className={s.quantity<=s.minimum?"font-bold text-destructive":"font-bold text-success"}>{s.quantity}</span><span className="text-xs text-muted-foreground"> / mín. {s.minimum}</span></td><td className="px-3 py-4"><div>{money(s.cost)}</div><div className="text-xs text-muted-foreground">Venda {money(s.price)}</div></td><td className="px-5 py-4"><Button variant="outline" size="sm" onClick={()=>onMove(s)}><ArrowDownToLine/>Entrada / saída</Button></td></tr>)}</tbody></table>{!stock.length&&<Empty text="Nenhuma peça encontrada."/>}</div></section></div>}
function WarrantyView({warranties,onNew,onView}:{warranties:Warranty[];onNew:()=>void;onView:(w:Warranty)=>void}){return <section className="rounded-lg border bg-card shadow-card"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-bold">Garantias emitidas</h2><p className="text-xs text-muted-foreground">Certificados vinculados às ordens de serviço</p></div><Button onClick={onNew}><Plus/>Emitir garantia</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr className="text-xs text-muted-foreground"><th className="px-5 py-3">CÓDIGO / ORDEM</th><th className="px-3 py-3">CLIENTE / EQUIPAMENTO</th><th className="px-3 py-3">VALIDADE</th><th className="px-5 py-3">DOCUMENTO</th></tr></thead><tbody>{warranties.map(w=><tr key={w.id} className="border-t"><td className="px-5 py-4 font-bold text-primary">{w.id}<div className="text-xs font-normal text-muted-foreground">{w.orderId}</div></td><td className="px-3 py-4"><div className="font-semibold">{w.customer}</div><div className="text-xs text-muted-foreground">{w.device}</div></td><td className="px-3 py-4">{w.starts} a {w.expires}</td><td className="px-5 py-4"><Button variant="outline" size="sm" onClick={()=>onView(w)}><FileDown/>Abrir certificado</Button></td></tr>)}</tbody></table></div></section>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-lg border bg-card p-5 shadow-card"><p className="text-xs font-semibold text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>}
function Empty({text}:{text:string}){return <div className="p-10 text-center text-sm text-muted-foreground">{text}</div>}
function Placeholder({section}:{section:Section}){return <div className="flex min-h-[430px] flex-col items-center justify-center rounded-lg border border-dashed bg-card px-6 text-center"><Building2 className="size-8 text-primary"/><h2 className="mt-5 text-xl font-bold">{section}</h2><p className="mt-2 max-w-md text-sm text-muted-foreground">Esta área mantém o controle administrativo já previsto para a plataforma.</p></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-1.5 text-sm font-semibold">{label}{children}</label>}
function FormActions({close,label}:{close:()=>void;label:string}){return <div className="mt-2 flex justify-end gap-2"><Button type="button" variant="outline" onClick={close}>Cancelar</Button><Button type="submit"><Check/>{label}</Button></div>}

function CustomerDialog({open,close,onSave}:{open:boolean;close:()=>void;onSave:(c:Customer)=>void}){return <Dialog open={open} onOpenChange={v=>!v&&close()}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>Novo cliente</DialogTitle><DialogDescription>Cadastre nome e documento em campos separados para localizar o cliente nas ordens.</DialogDescription></DialogHeader><form className="grid gap-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({id:crypto.randomUUID(),name:String(f.get("name")),document:String(f.get("document")),phone:String(f.get("phone")),email:String(f.get("email"))})}}><div className="grid gap-4 sm:grid-cols-2"><Field label="Nome / razão social"><Input name="name" required placeholder="Nome completo"/></Field><Field label="CPF / CNPJ"><Input name="document" required placeholder="000.000.000-00"/></Field><Field label="Telefone"><Input name="phone" required placeholder="(45) 99999-9999"/></Field><Field label="E-mail"><Input name="email" type="email" placeholder="cliente@email.com"/></Field></div><Field label="Endereço"><Input name="address" placeholder="Rua, número, bairro e cidade"/></Field><Field label="Observações"><Textarea name="notes" placeholder="Preferências e informações importantes"/></Field><FormActions close={close} label="Cadastrar cliente"/></form></DialogContent></Dialog>}
function StockDialog({open,close,onSave}:{open:boolean;close:()=>void;onSave:(s:Stock)=>void}){return <Dialog open={open} onOpenChange={v=>!v&&close()}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Nova peça ou produto</DialogTitle><DialogDescription>Defina saldo inicial, estoque mínimo, custos e localização.</DialogDescription></DialogHeader><form className="grid gap-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),qty=Number(f.get("quantity"));onSave({id:crypto.randomUUID(),sku:String(f.get("sku")),name:String(f.get("name")),category:String(f.get("category")),supplier:String(f.get("supplier")),location:String(f.get("location")),quantity:qty,minimum:Number(f.get("minimum")),cost:Number(f.get("cost")),price:Number(f.get("price")),movements:qty?[{type:"Entrada",quantity:qty,date:today(),note:"Saldo inicial"}]:[]})}}><div className="grid gap-4 sm:grid-cols-2"><Field label="Nome da peça"><Input name="name" required placeholder="Ex.: Conector de carga"/></Field><Field label="SKU / código"><Input name="sku" required placeholder="CON-IP14"/></Field><Field label="Categoria"><Input name="category" required placeholder="Conectores"/></Field><Field label="Fornecedor"><Input name="supplier" placeholder="Nome do fornecedor"/></Field><Field label="Localização"><Input name="location" placeholder="A-01"/></Field><Field label="Saldo inicial"><Input name="quantity" type="number" min="0" step="1" defaultValue="0" required/></Field><Field label="Estoque mínimo"><Input name="minimum" type="number" min="0" step="1" defaultValue="1" required/></Field><Field label="Custo unitário"><Input name="cost" type="number" min="0" step="0.01" required/></Field><Field label="Preço de venda"><Input name="price" type="number" min="0" step="0.01" required/></Field></div><FormActions close={close} label="Cadastrar peça"/></form></DialogContent></Dialog>}
function MovementDialog({open,item,close,onSave}:{open:boolean;item:Stock|null;close:()=>void;onSave:(id:string,n:number,t:string,note:string)=>void}){const [type,setType]=useState("entry");if(!item)return null;return <Dialog open={open} onOpenChange={v=>!v&&close()}><DialogContent><DialogHeader><DialogTitle>Movimentar estoque</DialogTitle><DialogDescription>{item.name} • saldo atual: {item.quantity}</DialogDescription></DialogHeader><form className="grid gap-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),n=Number(f.get("quantity"));if(type==="exit"&&n>item.quantity){alert("A saída não pode ser maior que o saldo disponível.");return}onSave(item.id,n,type,String(f.get("note")))}}><div className="grid grid-cols-2 gap-2"><Button type="button" variant={type==="entry"?"default":"outline"} onClick={()=>setType("entry")}><Plus/>Entrada</Button><Button type="button" variant={type==="exit"?"default":"outline"} onClick={()=>setType("exit")}><Minus/>Saída</Button></div><Field label="Quantidade"><Input name="quantity" type="number" min="1" max={type==="exit"?item.quantity:undefined} required/></Field><Field label="Motivo / referência"><Input name="note" required placeholder="Compra, ajuste, perda…"/></Field><div className="rounded-md bg-muted p-3"><p className="text-xs font-bold">Últimas movimentações</p>{item.movements.slice(0,3).map((m,i)=><p key={i} className="mt-2 text-xs text-muted-foreground">{m.date} • {m.type} • {m.quantity} un. • {m.note}</p>)}</div><FormActions close={close} label="Registrar movimentação"/></form></DialogContent></Dialog>}
function CustomerPicker({customers,onSelect}:{customers:Customer[];onSelect:(id:string)=>void}){const [open,setOpen]=useState(false),[term,setTerm]=useState(""),[chosen,setChosen]=useState<Customer|null>(null);const found=customers.filter(c=>`${c.name} ${c.document}`.toLowerCase().includes(term.toLowerCase()));return <div className="relative"><span className="mb-1.5 block text-sm font-semibold">Cliente</span><Button type="button" variant="outline" className="h-auto min-h-10 w-full justify-between text-left font-normal" onClick={()=>setOpen(v=>!v)}><span>{chosen?<><b>{chosen.name}</b><span className="ml-2 text-muted-foreground">{chosen.document}</span></>:"Selecione pelo nome ou documento"}</span><ChevronDown className="size-4 shrink-0"/></Button>{open&&<div className="absolute z-20 mt-1 w-full rounded-md border bg-popover p-2 shadow-lg"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input autoFocus value={term} onChange={e=>setTerm(e.target.value)} placeholder="Pesquisar nome, CPF ou CNPJ" className="pl-9"/></div><div className="mt-2 max-h-48 overflow-y-auto">{found.map(c=><Button key={c.id} type="button" variant="ghost" className="h-auto w-full justify-start py-2 text-left" onClick={()=>{setChosen(c);onSelect(c.id);setOpen(false)}}><span><b className="block">{c.name}</b><small className="text-muted-foreground">{c.document}</small></span></Button>)}{!found.length&&<p className="p-3 text-sm text-muted-foreground">Nenhum cliente encontrado.</p>}</div></div>}</div>}
function OrderDialog({open,customers,stock,close,onSave}:{open:boolean;customers:Customer[];stock:Stock[];close:()=>void;onSave:(o:Order,p:{id:string;quantity:number}|null)=>void}){const [customerId,setCustomerId]=useState(""),[partId,setPartId]=useState("");return <Dialog open={open} onOpenChange={v=>!v&&close()}><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>Nova ordem de serviço</DialogTitle><DialogDescription>Selecione um cliente já cadastrado e registre o equipamento, defeito e peças usadas.</DialogDescription></DialogHeader><form className="grid gap-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),c=customers.find(x=>x.id===customerId);if(!c){alert("Selecione um cliente cadastrado.");return}const part=stock.find(x=>x.id===partId),qty=Number(f.get("partQuantity")||0);if(part&&qty>part.quantity){alert("A quantidade da peça é maior que o saldo disponível.");return}const id=`OS-${1049+Math.floor(Math.random()*800)}`,parts=part&&qty?[{name:part.name,quantity:qty,price:part.price}]:[],total=Number(f.get("serviceValue")||0)+parts.reduce((a,p)=>a+p.quantity*p.price,0);onSave({id,customerId:c.id,client:c.name,document:c.document,device:`${String(f.get("brand"))} ${String(f.get("model"))}`,serial:String(f.get("serial")),issue:String(f.get("issue")),stage:"Recebida",tech:"Não atribuído",total,due:String(f.get("due")||"A definir"),tone:"slate",parts},part&&qty?{id:part.id,quantity:qty}:null)}}><CustomerPicker customers={customers} onSelect={setCustomerId}/><div className="grid gap-4 sm:grid-cols-2"><Field label="Categoria do equipamento"><Input name="category" required placeholder="Smartphone, notebook…"/></Field><Field label="Marca"><Input name="brand" required placeholder="Apple, Samsung, Dell…"/></Field><Field label="Modelo"><Input name="model" required placeholder="Modelo exato"/></Field><Field label="Número de série / IMEI"><Input name="serial" placeholder="Identificação do aparelho"/></Field></div><Field label="Defeito relatado"><Textarea name="issue" required placeholder="Descreva o problema informado pelo cliente"/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Peça do estoque (opcional)"><select name="part" value={partId} onChange={e=>setPartId(e.target.value)} className="h-10 rounded-md border bg-background px-3 text-sm"><option value="">Nenhuma peça</option>{stock.filter(s=>s.quantity>0).map(s=><option key={s.id} value={s.id}>{s.name} — saldo {s.quantity}</option>)}</select></Field><Field label="Quantidade da peça"><Input name="partQuantity" type="number" min="0" defaultValue="0"/></Field><Field label="Valor do serviço"><Input name="serviceValue" type="number" min="0" step="0.01" defaultValue="0"/></Field><Field label="Previsão"><Input name="due" type="date"/></Field></div><FormActions close={close} label="Criar ordem"/></form></DialogContent></Dialog>}
function WarrantyDialog({open,orders,close,onSave}:{open:boolean;orders:Order[];close:()=>void;onSave:(w:Warranty)=>void}){return <Dialog open={open} onOpenChange={v=>!v&&close()}><DialogContent><DialogHeader><DialogTitle>Emitir garantia</DialogTitle><DialogDescription>Crie o certificado a partir de uma ordem de serviço.</DialogDescription></DialogHeader><form className="grid gap-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),o=orders.find(x=>x.id===f.get("order"));if(!o)return;const days=Number(f.get("days"));onSave({id:`GAR-${crypto.randomUUID().slice(0,6).toUpperCase()}`,orderId:o.id,customer:o.client,device:o.device,starts:today(),expires:addDays(days),coverage:String(f.get("coverage")),status:"Ativa"})}}><Field label="Ordem de serviço"><select name="order" required className="h-10 rounded-md border bg-background px-3 text-sm"><option value="">Selecione a ordem</option>{orders.map(o=><option key={o.id} value={o.id}>{o.id} — {o.client} — {o.device}</option>)}</select></Field><Field label="Prazo de garantia"><select name="days" className="h-10 rounded-md border bg-background px-3 text-sm"><option value="30">30 dias</option><option value="90">90 dias</option><option value="180">180 dias</option><option value="365">1 ano</option></select></Field><Field label="Cobertura"><Textarea name="coverage" required placeholder="Serviços e peças cobertos"/></Field><Field label="Condições e exclusões"><Textarea name="terms" placeholder="Mau uso, líquidos, danos físicos…"/></Field><FormActions close={close} label="Emitir garantia"/></form></DialogContent></Dialog>}
function OrderDocumentDialog({open,order,close}:{open:boolean;order:Order|null;close:()=>void}){if(!order)return null;const body=`<h1>Ordem de serviço ${escapeHtml(order.id)}</h1><div class="muted">Emitida em ${today()}</div><h2>Cliente</h2><div class="grid"><div><b>Nome</b><br>${escapeHtml(order.client)}</div><div><b>Documento</b><br>${escapeHtml(order.document)}</div></div><h2>Equipamento</h2><div class="grid"><div><b>Equipamento</b><br>${escapeHtml(order.device)}</div><div><b>Série / IMEI</b><br>${escapeHtml(order.serial||"Não informado")}</div></div><h2>Defeito relatado</h2><div class="box">${escapeHtml(order.issue)}</div><h2>Itens e valores</h2>${order.parts.map(p=>`<div class="row"><span>${p.quantity}x ${escapeHtml(p.name)}</span><b>${money(p.quantity*p.price)}</b></div>`).join("")}<div class="row total"><span>Total da ordem</span><span>${money(order.total)}</span></div><h2>Situação</h2><div class="box">${escapeHtml(order.stage)} • Previsão: ${escapeHtml(order.due)}</div>`;return <DocumentDialog open={open} close={close} title={`Ordem ${order.id}`} subtitle={`${order.client} • ${order.device}`} onPrint={()=>printDocument(`Ordem ${order.id}`,body)}><div className="grid gap-4 sm:grid-cols-2"><DocItem label="Cliente" value={order.client}/><DocItem label="Documento" value={order.document}/><DocItem label="Equipamento" value={order.device}/><DocItem label="Série / IMEI" value={order.serial||"Não informado"}/></div><div className="rounded-md bg-muted p-4"><p className="text-xs font-bold text-muted-foreground">DEFEITO RELATADO</p><p className="mt-1 text-sm">{order.issue}</p></div><div className="flex justify-between border-t pt-4 font-bold"><span>Total</span><span>{money(order.total)}</span></div></DocumentDialog>}
function WarrantyDocumentDialog({open,warranty,close}:{open:boolean;warranty:Warranty|null;close:()=>void}){if(!warranty)return null;const body=`<h1>Certificado de garantia</h1><div class="muted">Código de autenticidade: ${escapeHtml(warranty.id)}</div><h2>Referência</h2><div class="grid"><div><b>Ordem</b><br>${escapeHtml(warranty.orderId)}</div><div><b>Cliente</b><br>${escapeHtml(warranty.customer)}</div><div><b>Equipamento</b><br>${escapeHtml(warranty.device)}</div><div><b>Validade</b><br>${escapeHtml(warranty.starts)} a ${escapeHtml(warranty.expires)}</div></div><h2>Cobertura</h2><div class="box">${escapeHtml(warranty.coverage)}</div><h2>Condições gerais</h2><div class="box">A garantia cobre exclusivamente os serviços e peças descritos neste certificado. Danos por mau uso, líquidos, quedas, violação ou intervenção de terceiros não estão cobertos.</div>`;return <DocumentDialog open={open} close={close} title="Certificado de garantia" subtitle={`${warranty.id} • ${warranty.orderId}`} onPrint={()=>printDocument(`Garantia ${warranty.id}`,body)}><div className="grid gap-4 sm:grid-cols-2"><DocItem label="Cliente" value={warranty.customer}/><DocItem label="Equipamento" value={warranty.device}/><DocItem label="Início" value={warranty.starts}/><DocItem label="Validade" value={warranty.expires}/></div><div className="rounded-md bg-muted p-4"><p className="text-xs font-bold text-muted-foreground">COBERTURA</p><p className="mt-1 text-sm">{warranty.coverage}</p></div></DocumentDialog>}
function DocumentDialog({open,close,title,subtitle,onPrint,children}:{open:boolean;close:()=>void;title:string;subtitle:string;onPrint:()=>void;children:React.ReactNode}){return <Dialog open={open} onOpenChange={v=>!v&&close()}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{subtitle}</DialogDescription></DialogHeader><div className="grid gap-4">{children}<div className="flex flex-col-reverse gap-2 border-t pt-4 sm:flex-row sm:justify-end"><Button variant="outline" onClick={close}>Fechar</Button><Button onClick={onPrint}><Printer/>Imprimir / Salvar PDF</Button></div></div></DialogContent></Dialog>}
function DocItem({label,value}:{label:string;value:string}){return <div><p className="text-xs font-bold text-muted-foreground">{label.toUpperCase()}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>}
