import { useMemo, useState, type FormEvent } from "react";
import { Plus, Pencil, Trash2, FileDown, Receipt } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";

type Entry = {id:string;entry_type:string;department:string;category:string;description:string;amount:number;payment_method:string|null;entry_date:string;status?:string};
type Company = {name:string;document:string;phone:string;address:string;email:string;logoUrl:string};
type Period = {from:string;to:string};
const money=(n:number)=>Number(n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const key=(value:string)=>{if(/^\d{4}-\d{2}-\d{2}$/.test(value||""))return value;const d=new Date(value);if(Number.isNaN(d.getTime()))return "";return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")};
const today=()=>{const d=new Date();return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")};
const safe=(v:string)=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]||c));
const categories=[{value:"parts",label:"Compra de peças"},{value:"store",label:"Compra de produtos da loja"},{value:"supplier",label:"Fornecedor"},{value:"unexpected",label:"Imprevistos"},{value:"loss",label:"Prejuízos"},{value:"other",label:"Outros"}];
const payLabel=(v:string|null)=>({cash:"Dinheiro",pix:"Pix",credit_card:"Cartão de crédito",debit_card:"Cartão de débito",transfer:"Transferência",other:"Outro"} as Record<string,string>)[v||""]||"Não informado";

export function ExpensesView({entries,organizationId,company,onChanged}:{entries:Entry[];organizationId:string|null;company:Company;onChanged:()=>Promise<void>}) {
  const [range,setRange]=useState<Period>({from:"",to:""});
  const [open,setOpen]=useState(false);
  const [editing,setEditing]=useState<Entry|null>(null);
  const [category,setCategory]=useState("parts");
  const [customCategory,setCustomCategory]=useState("");
  const [description,setDescription]=useState("");
  const [amount,setAmount]=useState("");
  const [date,setDate]=useState(today());
  const [payment,setPayment]=useState("pix");
  const [customPayment,setCustomPayment]=useState("");
  const [notes,setNotes]=useState("");
  const [saving,setSaving]=useState(false);
  const expenses=useMemo(()=>entries.filter(e=>e.entry_type==="expense"&&(!range.from||key(e.entry_date)>=range.from)&&(!range.to||key(e.entry_date)<=range.to)).sort((a,b)=>key(b.entry_date).localeCompare(key(a.entry_date))),[entries,range]);
  const total=expenses.reduce((sum,e)=>sum+Number(e.amount||0),0);
  const startNew=()=>{setEditing(null);setCategory("parts");setCustomCategory("");setDescription("");setAmount("");setDate(today());setPayment("pix");setCustomPayment("");setNotes("");setOpen(true)};
  const startEdit=(e:Entry)=>{setEditing(e);setCategory(categories.some(c=>c.value===e.department)?e.department:"other");setCustomCategory(categories.some(c=>c.label===e.category)? "":e.category||"");const descriptionText=e.description||"";const paymentMatch=descriptionText.match(/ — Forma de pagamento: (.+)$/);setDescription(paymentMatch?descriptionText.replace(/ — Forma de pagamento: .+$/,""):descriptionText);setAmount(String(e.amount));setDate(key(e.entry_date)||today());setPayment(e.payment_method||"other");setCustomPayment(paymentMatch?.[1]??"");setNotes("");setOpen(true)};
  const save=async(e:FormEvent)=>{e.preventDefault();if(!organizationId){alert("Esta conta não está vinculada a uma empresa.");return}const value=Number(amount);if(!Number.isFinite(value)||value<=0){alert("Informe um valor de despesa maior que zero.");return}const label=category==="other"?(customCategory.trim()||"Outros"):(categories.find(c=>c.value===category)?.label||customCategory.trim()||"Outros");const payload={entry_type:"expense",department:category,category:label,description:(description.trim()||label)+(notes.trim()?" — "+notes.trim():"")+(payment==="other"&&customPayment.trim()?" — Forma de pagamento: "+customPayment.trim():""),amount:value,payment_method:payment,entry_date:date};
    setSaving(true);
    const {data:userData}=await supabase.auth.getUser();
    const result=editing?await supabase.from("financial_entries").update(payload).eq("id",editing.id).eq("organization_id",organizationId):await supabase.from("financial_entries").insert({...payload,organization_id:organizationId,sale_id:null,created_by:userData.user?.id??null});
    setSaving(false);
    if(result.error){alert("Não foi possível salvar a despesa: "+result.error.message);return}
    setOpen(false);await onChanged();
  };
  const remove=async(e:Entry)=>{if(!organizationId||!window.confirm("Excluir esta despesa? Essa ação não pode ser desfeita."))return;const {error}=await supabase.from("financial_entries").delete().eq("id",e.id).eq("organization_id",organizationId);if(error){alert("Não foi possível excluir a despesa: "+error.message);return}await onChanged()};
  const print=()=>{const rows=expenses.map(e=>`<tr><td>${safe(new Date(key(e.entry_date)+"T12:00:00").toLocaleDateString("pt-BR"))}</td><td>${safe(e.category||"Outros")}</td><td>${safe(e.description||"—")}</td><td>${safe(payLabel(e.payment_method))}</td><td class="value">${money(e.amount)}</td></tr>`).join("");const html=`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Relatório de despesas</title><style>@page{size:A4;margin:16mm}body{font-family:Arial,sans-serif;color:#172033;font-size:12px}.head{border-bottom:3px solid #b45309;padding-bottom:12px;margin-bottom:20px}.muted{color:#667085}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{padding:9px;border-bottom:1px solid #ddd;text-align:left}th{background:#f8fafc}.value{text-align:right;font-weight:bold}.total{text-align:right;font-size:18px;font-weight:bold;margin-top:20px}</style></head><body><div class="head"><h1>${safe(company.name||"Sua empresa")}</h1><div class="muted">Relatório de despesas • ${range.from?new Date(range.from+"T12:00:00").toLocaleDateString("pt-BR"):"Início"} a ${range.to?new Date(range.to+"T12:00:00").toLocaleDateString("pt-BR"):"Hoje"}</div></div><table><thead><tr><th>DATA</th><th>CATEGORIA</th><th>DESCRIÇÃO</th><th>PAGAMENTO</th><th>VALOR</th></tr></thead><tbody>${rows}</tbody></table><div class="total">Total de despesas: ${money(total)}</div><p class="muted">Relatório gerado em ${new Date().toLocaleString("pt-BR")}.</p><script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`;const w=window.open("about:blank","_blank");if(!w){alert("Permita pop-ups para gerar o relatório.");return}w.document.write(html);w.document.close()};
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-extrabold">Despesas</h2><p className="mt-1 text-sm text-muted-foreground">Registre compras, fornecedores, imprevistos, prejuízos e outros gastos.</p></div><Button onClick={startNew}><Plus/>Registrar despesa</Button></div>
    <section className="rounded-xl border bg-card p-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="font-bold">Período do relatório</h3><p className="text-xs text-muted-foreground">Filtre por data e gere uma versão para imprimir ou salvar em PDF.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={()=>setRange({from:"",to:""})}>Todos</Button><Button variant="outline" size="sm" onClick={()=>setRange({from:today(),to:today()})}>Hoje</Button><Button variant="outline" size="sm" onClick={()=>{const d=new Date();d.setDate(d.getDate()-6);setRange({from:key(d.toISOString()),to:today()})}}>7 dias</Button><Button variant="outline" size="sm" onClick={()=>{const d=new Date();d.setDate(d.getDate()-29);setRange({from:key(d.toISOString()),to:today()})}}>30 dias</Button></div></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-xs font-semibold">Data inicial<Input type="date" value={range.from} onChange={e=>setRange(v=>({...v,from:e.target.value}))}/></label><label className="grid gap-1 text-xs font-semibold">Data final<Input type="date" value={range.to} onChange={e=>setRange(v=>({...v,to:e.target.value}))}/></label></div></section>
    <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border bg-card p-5"><p className="text-sm text-muted-foreground">Total no período</p><p className="mt-2 text-2xl font-extrabold">{money(total)}</p></div><div className="rounded-xl border bg-card p-5"><p className="text-sm text-muted-foreground">Despesas registradas</p><p className="mt-2 text-2xl font-extrabold">{expenses.length}</p></div><div className="flex flex-col justify-between rounded-xl border bg-card p-5"><p className="text-sm text-muted-foreground">Relatório de despesas</p><Button variant="outline" className="mt-3" onClick={print}><FileDown/>Imprimir / Salvar PDF</Button></div></div>
    <section className="overflow-hidden rounded-xl border bg-card"><div className="border-b p-4"><h3 className="font-bold">Histórico de despesas</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[750px] text-left text-sm"><thead><tr className="bg-muted/40 text-xs text-muted-foreground"><th className="p-4">DATA</th><th className="p-4">CATEGORIA</th><th className="p-4">DESCRIÇÃO</th><th className="p-4">PAGAMENTO</th><th className="p-4">VALOR</th><th className="p-4">AÇÕES</th></tr></thead><tbody>{expenses.map(e=><tr key={e.id} className="border-t"><td className="p-4">{key(e.entry_date)?new Date(key(e.entry_date)+"T12:00:00").toLocaleDateString("pt-BR"):"—"}</td><td className="p-4">{e.category||"Outros"}</td><td className="p-4">{e.description||"—"}</td><td className="p-4">{payLabel(e.payment_method)}</td><td className="p-4 font-bold">{money(e.amount)}</td><td className="p-3"><div className="flex gap-1"><Button variant="ghost" size="icon" title="Editar despesa" onClick={()=>startEdit(e)}><Pencil className="size-4"/></Button><Button variant="ghost" size="icon" title="Excluir despesa" onClick={()=>remove(e)}><Trash2 className="size-4 text-destructive"/></Button></div></td></tr>)}</tbody></table>{!expenses.length&&<div className="p-10 text-center text-sm text-muted-foreground">Nenhuma despesa registrada neste período.</div>}</div></section>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{editing?"Editar despesa":"Registrar despesa"}</DialogTitle><DialogDescription>Despesas ficam no financeiro e aparecem nos relatórios do período selecionado.</DialogDescription></DialogHeader><form className="grid gap-4" onSubmit={save}><label className="grid gap-1 text-sm font-semibold">Categoria<select className="h-10 rounded-md border bg-background px-3" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c.value} value={c.value}>{c.label}</option>)}</select></label>{category==="other"&&<label className="grid gap-1 text-sm font-semibold">Qual é a despesa?<Input value={customCategory} onChange={e=>setCustomCategory(e.target.value)} placeholder="Escreva a categoria" required/></label>}<label className="grid gap-1 text-sm font-semibold">Descrição / fornecedor<Input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Ex.: compra de telas com fornecedor X" required/></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm font-semibold">Valor (R$)<Input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label className="grid gap-1 text-sm font-semibold">Data da despesa<Input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label></div><label className="grid gap-1 text-sm font-semibold">Forma de pagamento<select className="h-10 rounded-md border bg-background px-3" value={payment} onChange={e=>setPayment(e.target.value)}><option value="pix">Pix</option><option value="cash">Dinheiro</option><option value="credit_card">Cartão de crédito</option><option value="debit_card">Cartão de débito</option><option value="transfer">Transferência</option><option value="other">Outro</option></select></label>{payment==="other"&&<label className="grid gap-1 text-sm font-semibold">Descreva a forma de pagamento<Input value={customPayment} onChange={e=>setCustomPayment(e.target.value)} placeholder="Ex.: boleto, cheque, permuta" required/></label>}<label className="grid gap-1 text-sm font-semibold">Observações (opcional)<Textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Detalhes adicionais"/></label><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button type="submit" disabled={saving}>{saving?"Salvando…":editing?"Salvar alterações":"Salvar despesa"}</Button></div></form></DialogContent></Dialog>
  </div>;
}
