-- Sales and finance ledger for Service Pro Hub.
-- All records are organization-scoped. Sale creation and stock deduction happen atomically
-- through create_pos_sale so a partial sale cannot leave inventory inconsistent.

CREATE TABLE IF NOT EXISTS public.sales (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  sale_number bigint GENERATED BY DEFAULT AS IDENTITY,
  sale_type text NOT NULL CHECK (sale_type IN ('pos','quick')),
  department text NOT NULL CHECK (department IN ('assistance','parts','store')),
  customer_id uuid REFERENCES public.customers(id) ON DELETE SET NULL,
  subtotal numeric(12,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
  discount numeric(12,2) NOT NULL DEFAULT 0 CHECK (discount >= 0),
  total numeric(12,2) NOT NULL DEFAULT 0 CHECK (total >= 0),
  payment_method text NOT NULL CHECK (payment_method IN ('cash','pix','credit_card','debit_card','transfer','other')),
  notes text,
  sold_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (discount <= subtotal),
  UNIQUE (organization_id, sale_number)
);

CREATE TABLE IF NOT EXISTS public.sale_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  sale_id uuid NOT NULL REFERENCES public.sales(id) ON DELETE CASCADE,
  inventory_item_id uuid REFERENCES public.inventory_items(id) ON DELETE RESTRICT,
  description text NOT NULL,
  quantity numeric(12,3) NOT NULL CHECK (quantity > 0),
  unit_price numeric(12,2) NOT NULL CHECK (unit_price >= 0),
  unit_cost numeric(12,2) NOT NULL DEFAULT 0 CHECK (unit_cost >= 0),
  line_total numeric(12,2) NOT NULL CHECK (line_total >= 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.financial_entries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  sale_id uuid REFERENCES public.sales(id) ON DELETE SET NULL,
  entry_type text NOT NULL CHECK (entry_type IN ('income','expense')),
  department text NOT NULL CHECK (department IN ('assistance','parts','store','general')),
  category text NOT NULL,
  description text NOT NULL,
  amount numeric(12,2) NOT NULL CHECK (amount > 0),
  payment_method text,
  entry_date date NOT NULL DEFAULT CURRENT_DATE,
  notes text,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS sales_org_date_idx ON public.sales (organization_id, sold_at DESC);
CREATE INDEX IF NOT EXISTS sale_items_sale_idx ON public.sale_items (organization_id, sale_id);
CREATE INDEX IF NOT EXISTS financial_entries_org_date_idx ON public.financial_entries (organization_id, entry_date DESC);

ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_entries ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS sales_org_access ON public.sales;
CREATE POLICY sales_org_access ON public.sales
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.organization_members m WHERE m.organization_id=sales.organization_id AND m.user_id=auth.uid() AND m.active=true))
  WITH CHECK (EXISTS (SELECT 1 FROM public.organization_members m WHERE m.organization_id=sales.organization_id AND m.user_id=auth.uid() AND m.active=true));

DROP POLICY IF EXISTS sale_items_org_access ON public.sale_items;
CREATE POLICY sale_items_org_access ON public.sale_items
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.organization_members m WHERE m.organization_id=sale_items.organization_id AND m.user_id=auth.uid() AND m.active=true))
  WITH CHECK (EXISTS (SELECT 1 FROM public.organization_members m WHERE m.organization_id=sale_items.organization_id AND m.user_id=auth.uid() AND m.active=true));

DROP POLICY IF EXISTS financial_entries_org_access ON public.financial_entries;
CREATE POLICY financial_entries_org_access ON public.financial_entries
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.organization_members m WHERE m.organization_id=financial_entries.organization_id AND m.user_id=auth.uid() AND m.active=true))
  WITH CHECK (EXISTS (SELECT 1 FROM public.organization_members m WHERE m.organization_id=financial_entries.organization_id AND m.user_id=auth.uid() AND m.active=true));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.sales, public.sale_items, public.financial_entries TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- Atomically validates organization membership, records a sale and its line items,
-- decrements stock for linked items, and posts the income ledger entry.
CREATE OR REPLACE FUNCTION public.create_pos_sale(
  _organization_id uuid,
  _sale_type text,
  _department text,
  _customer_id uuid,
  _discount numeric,
  _payment_method text,
  _notes text,
  _items jsonb
) RETURNS uuid
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  _sale_id uuid;
  _subtotal numeric(12,2) := 0;
  _total numeric(12,2);
  _item jsonb;
  _inventory_id uuid;
  _qty numeric(12,3);
  _price numeric(12,2);
  _cost numeric(12,2);
  _name text;
  _stock public.inventory_items%ROWTYPE;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.organization_members m WHERE m.organization_id=_organization_id AND m.user_id=auth.uid() AND m.active=true) THEN
    RAISE EXCEPTION 'Acesso não autorizado à empresa';
  END IF;
  IF _sale_type NOT IN ('pos','quick') OR _department NOT IN ('assistance','parts','store') THEN
    RAISE EXCEPTION 'Tipo de venda ou setor inválido';
  END IF;
  IF _payment_method NOT IN ('cash','pix','credit_card','debit_card','transfer','other') THEN
    RAISE EXCEPTION 'Forma de pagamento inválida';
  END IF;
  IF _items IS NULL OR jsonb_typeof(_items) <> 'array' OR jsonb_array_length(_items)=0 THEN
    RAISE EXCEPTION 'Adicione ao menos um item à venda';
  END IF;

  FOR _item IN SELECT value FROM jsonb_array_elements(_items)
  LOOP
    _qty := (_item->>'quantity')::numeric;
    _price := (_item->>'unit_price')::numeric;
    IF _qty <= 0 OR _price < 0 THEN RAISE EXCEPTION 'Quantidade ou preço inválido'; END IF;
    _inventory_id := NULLIF(_item->>'inventory_item_id','')::uuid;
    IF _inventory_id IS NOT NULL THEN
      SELECT * INTO _stock FROM public.inventory_items
      WHERE id=_inventory_id AND organization_id=_organization_id AND active=true
      FOR UPDATE;
      IF NOT FOUND THEN RAISE EXCEPTION 'Item de estoque não encontrado nesta empresa'; END IF;
      IF _stock.quantity < _qty THEN RAISE EXCEPTION 'Estoque insuficiente para: %', _stock.name; END IF;
      _name := _stock.name;
      _cost := coalesce(_stock.cost,0);
    ELSE
      _name := coalesce(nullif(_item->>'description',''),'Item avulso');
      _cost := coalesce((_item->>'unit_cost')::numeric,0);
    END IF;
    _subtotal := _subtotal + (_qty * _price);
  END LOOP;

  IF coalesce(_discount,0)<0 OR coalesce(_discount,0)>_subtotal THEN RAISE EXCEPTION 'Desconto inválido'; END IF;
  _total := _subtotal - coalesce(_discount,0);

  INSERT INTO public.sales (organization_id,sale_type,department,customer_id,subtotal,discount,total,payment_method,notes,created_by)
  VALUES (_organization_id,_sale_type,_department,_customer_id,_subtotal,coalesce(_discount,0),_total,_payment_method,_notes,auth.uid())
  RETURNING id INTO _sale_id;

  FOR _item IN SELECT value FROM jsonb_array_elements(_items)
  LOOP
    _qty := (_item->>'quantity')::numeric;
    _price := (_item->>'unit_price')::numeric;
    _inventory_id := NULLIF(_item->>'inventory_item_id','')::uuid;
    IF _inventory_id IS NOT NULL THEN
      SELECT * INTO _stock FROM public.inventory_items
      WHERE id=_inventory_id AND organization_id=_organization_id AND active=true
      FOR UPDATE;
      _name := _stock.name;
      _cost := coalesce(_stock.cost,0);
      UPDATE public.inventory_items SET quantity=quantity-_qty, updated_at=now()
      WHERE id=_inventory_id AND organization_id=_organization_id;
      INSERT INTO public.inventory_movements (organization_id,inventory_item_id,movement_type,quantity,unit_cost,notes,created_by)
      VALUES (_organization_id,_inventory_id,'exit',_qty,_cost,'Venda #'||_sale_id::text,auth.uid());
    ELSE
      _name := coalesce(nullif(_item->>'description',''),'Item avulso');
      _cost := coalesce((_item->>'unit_cost')::numeric,0);
    END IF;
    INSERT INTO public.sale_items (organization_id,sale_id,inventory_item_id,description,quantity,unit_price,unit_cost,line_total)
    VALUES (_organization_id,_sale_id,_inventory_id,_name,_qty,_price,_cost,_qty*_price);
  END LOOP;

  IF _total > 0 THEN
    INSERT INTO public.financial_entries (organization_id,sale_id,entry_type,department,category,description,amount,payment_method,created_by)
    VALUES (_organization_id,_sale_id,'income',_department,'Venda','Venda registrada no sistema',_total,_payment_method,auth.uid());
  END IF;
  RETURN _sale_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.create_pos_sale(uuid,text,text,uuid,numeric,text,text,jsonb) TO authenticated;
